#!/bin/sh
set -e

update-alternatives --quiet --remove runlevel /usr/bin/systemctl
update-alternatives --quiet --remove reboot /usr/bin/systemctl
update-alternatives --quiet --remove shutdown /usr/bin/systemctl
update-alternatives --quiet --remove poweroff /usr/bin/systemctl
update-alternatives --quiet --remove halt /usr/bin/systemctl
update-alternatives --quiet --remove telinit /usr/bin/systemctl
update-alternatives --quiet --remove init /usr/lib/systemd/systemd

