#!/bin/sh
set -e

update-alternatives --quiet --remove lzcat /usr/bin/xz.xz
update-alternatives --quiet --remove lzcmp /usr/bin/xzdiff.xz
update-alternatives --quiet --remove lzdiff /usr/bin/xzdiff.xz
update-alternatives --quiet --remove lzegrep /usr/bin/xzgrep.xz
update-alternatives --quiet --remove lzfgrep /usr/bin/xzgrep.xz
update-alternatives --quiet --remove lzgrep /usr/bin/xzgrep.xz
update-alternatives --quiet --remove lzless /usr/bin/xzless.xz
update-alternatives --quiet --remove lzmadec /usr/bin/lzmadec.xz
update-alternatives --quiet --remove lzmainfo /usr/bin/lzmainfo.xz
update-alternatives --quiet --remove lzma /usr/bin/xz.xz
update-alternatives --quiet --remove lzmore /usr/bin/xzmore.xz
update-alternatives --quiet --remove unlzma /usr/bin/xz.xz
update-alternatives --quiet --remove unxz /usr/bin/xz.xz
update-alternatives --quiet --remove xz /usr/bin/xz.xz
update-alternatives --quiet --remove xzcat /usr/bin/xz.xz
update-alternatives --quiet --remove xzcmp /usr/bin/xzdiff.xz
update-alternatives --quiet --remove xzdec /usr/bin/xzdec.xz
update-alternatives --quiet --remove xzdiff /usr/bin/xzdiff.xz
update-alternatives --quiet --remove xzegrep /usr/bin/xzgrep.xz
update-alternatives --quiet --remove xzfgrep /usr/bin/xzgrep.xz
update-alternatives --quiet --remove xzgrep /usr/bin/xzgrep.xz
update-alternatives --quiet --remove xzless /usr/bin/xzless.xz
update-alternatives --quiet --remove xzmore /usr/bin/xzmore.xz
