#!/bin/sh
set -e

JDK_HOME=/usr/lib/jvm/jdk-8-openjdk-amd64
JRE_HOME=/usr/lib/jvm/jdk-8-openjdk-amd64/jre

# javac
update-alternatives --quiet --install /usr/bin/javac javac ${JDK_HOME}/bin/javac 18060 \
	--slave /usr/bin/appletviewer appletviewer ${JDK_HOME}/bin/appletviewer \
	--slave /usr/bin/extcheck extcheck ${JDK_HOME}/bin/extcheck \
	--slave /usr/bin/idlj idlj ${JDK_HOME}/bin/idlj \
	--slave /usr/bin/jar jar ${JDK_HOME}/bin/jar \
	--slave /usr/bin/jarsigner jarsigner ${JDK_HOME}/bin/jarsigner \
	--slave /usr/bin/java-rmi.cgi java-rmi.cgi ${JDK_HOME}/bin/java-rmi.cgi \
	--slave /usr/bin/javac javac ${JDK_HOME}/bin/javac \
	--slave /usr/bin/javadoc javadoc ${JDK_HOME}/bin/javadoc \
	--slave /usr/bin/javah javah ${JDK_HOME}/bin/javah \
	--slave /usr/bin/javap javap ${JDK_HOME}/bin/javap \
	--slave /usr/bin/jcmd jcmd ${JDK_HOME}/bin/jcmd \
	--slave /usr/bin/jconsole jconsole ${JDK_HOME}/bin/jconsole \
	--slave /usr/bin/jdb jdb ${JDK_HOME}/bin/jdb \
	--slave /usr/bin/jdeps jdeps ${JDK_HOME}/bin/jdeps \
	--slave /usr/bin/jhat jhat ${JDK_HOME}/bin/jhat \
	--slave /usr/bin/jinfo jinfo ${JDK_HOME}/bin/jinfo \
	--slave /usr/bin/jmap jmap ${JDK_HOME}/bin/jmap \
	--slave /usr/bin/jps jps ${JDK_HOME}/bin/jps \
	--slave /usr/bin/jrunscript jrunscript ${JDK_HOME}/bin/jrunscript \
	--slave /usr/bin/jsadebugd jsadebugd ${JDK_HOME}/bin/jsadebugd \
	--slave /usr/bin/jstack jstack ${JDK_HOME}/bin/jstack \
	--slave /usr/bin/jstat jstat ${JDK_HOME}/bin/jstat \
	--slave /usr/bin/jstatd jstatd ${JDK_HOME}/bin/jstatd \
	--slave /usr/bin/native2ascii native2ascii ${JDK_HOME}/bin/native2ascii \
	--slave /usr/bin/rmic rmic ${JDK_HOME}/bin/rmic \
	--slave /usr/bin/schemagen schemagen ${JDK_HOME}/bin/schemagen \
	--slave /usr/bin/serialver serialver ${JDK_HOME}/bin/serialver \
	--slave /usr/bin/wsgen wsgen ${JDK_HOME}/bin/wsgen \
	--slave /usr/bin/wsimport wsimport ${JDK_HOME}/bin/wsimport \
	--slave /usr/bin/xjc xjc ${JDK_HOME}/bin/xjc

# java
update-alternatives --quiet --install /usr/bin/java java ${JRE_HOME}/java 118060 \
	--slave /usr/bin/java java ${JRE_HOME}/java \
	--slave /usr/bin/jjs jjs ${JRE_HOME}/jjs \
	--slave /usr/bin/keytool keytool ${JRE_HOME}/keytool \
	--slave /usr/bin/orbd orbd ${JRE_HOME}/orbd \
	--slave /usr/bin/pack200 pack200 ${JRE_HOME}/pack200 \
	--slave /usr/bin/policytool policytool ${JRE_HOME}/policytool \
	--slave /usr/bin/rmid rmid ${JRE_HOME}/rmid \
	--slave /usr/bin/rmiregistry rmiregistry ${JRE_HOME}/rmiregistry \
	--slave /usr/bin/servertool servertool ${JRE_HOME}/servertool \
	--slave /usr/bin/tnameserv tnameserv ${JRE_HOME}/tnameserv \
	--slave /usr/bin/unpack200 unpack200 ${JRE_HOME}/unpack200

update-alternatives --quiet --install /usr/lib/jvm/jdk jdk ${JDK_HOME} 18060
update-alternatives --quiet --install /usr/lib/jvm/jdk-8 jdk-8 ${JDK_HOME} 18060
update-alternatives --quiet --install /usr/lib/jvm/jdk-8u60 jdk-8u60 ${JDK_HOME} 18060

update-alternatives --quiet --install /usr/lib/jvm/jre jre ${JRE_HOME} 118060
update-alternatives --quiet --install /usr/lib/jvm/jre-8 jre-8 ${JRE_HOME} 118060
update-alternatives --quiet --install /usr/lib/jvm/jre-8u60 jre-8u60 ${JRE_HOME} 118060
