#!/bin/sh
set -e

JRE_HOME=/usr/lib/jvm/jre-8-openjdk-amd64

# java
update-alternatives --quiet --install /usr/bin/java java ${JRE_HOME}/bin/java 218092 \
	--slave /usr/bin/jjs jjs ${JRE_HOME}/bin/jjs \
	--slave /usr/bin/keytool keytool ${JRE_HOME}/bin/keytool \
	--slave /usr/bin/orbd orbd ${JRE_HOME}/bin/orbd \
	--slave /usr/bin/pack200 pack200 ${JRE_HOME}/bin/pack200 \
	--slave /usr/bin/policytool policytool ${JRE_HOME}/bin/policytool \
	--slave /usr/bin/rmid rmid ${JRE_HOME}/bin/rmid \
	--slave /usr/bin/rmiregistry rmiregistry ${JRE_HOME}/bin/rmiregistry \
	--slave /usr/bin/servertool servertool ${JRE_HOME}/bin/servertool \
	--slave /usr/bin/tnameserv tnameserv ${JRE_HOME}/bin/tnameserv \
	--slave /usr/bin/unpack200 unpack200 ${JRE_HOME}/bin/unpack200

update-alternatives --quiet --install /usr/lib/jvm/jre jre ${JRE_HOME} 218092
update-alternatives --quiet --install /usr/lib/jvm/jre-8 jre-8 ${JRE_HOME} 218092
update-alternatives --quiet --install /usr/lib/jvm/jre-8u92 jre-8u92 ${JRE_HOME} 218092
