#!/bin/sh
set -e

JRE_HOME=/usr/lib/jvm/jdk-8-openjdk-amd64/jre

# java
update-alternatives --quiet --install /usr/bin/java java ${JRE_HOME}/java 218060 \
	--slave /usr/bin/java java ${JRE_HOME}/java \
	--slave /usr/bin/jjs jjs ${JRE_HOME}/jjs \
	--slave /usr/bin/keytool keytool ${JRE_HOME}/keytool \
	--slave /usr/bin/orbd orbd ${JRE_HOME}/orbd \
	--slave /usr/bin/pack200 pack200 ${JRE_HOME}/pack200 \
	--slave /usr/bin/policytool policytool ${JRE_HOME}/policytool \
	--slave /usr/bin/rmid rmid ${JRE_HOME}/rmid \
	--slave /usr/bin/rmiregistry rmiregistry ${JRE_HOME}/rmiregistry \
	--slave /usr/bin/servertool servertool ${JRE_HOME}/servertool \
	--slave /usr/bin/tnameserv tnameserv ${JRE_HOME}/tnameserv \
	--slave /usr/bin/unpack200 unpack200 ${JRE_HOME}/unpack200

update-alternatives --quiet --install /usr/lib/jvm/jre jre ${JRE_HOME} 218060
update-alternatives --quiet --install /usr/lib/jvm/jre-8 jre-8 ${JRE_HOME} 218060
update-alternatives --quiet --install /usr/lib/jvm/jre-8u60 jre-8u60 ${JRE_HOME} 218060
