#!/bin/sh
set -e

update-alternatives --quiet --install /usr/bin/grep grep /usr/bin/grep.grep 100
update-alternatives --quiet --install /usr/bin/egrep egrep /usr/bin/egrep.grep 100
update-alternatives --quiet --install /usr/bin/fgrep fgrep /usr/bin/fgrep.grep 100
